### ISSUE TITLE
ElvUI Panels strata too high and covers other UI elements placed on them but only after exiting Pet Battles 

### ISSUE THREAD

**Issue by lyledouglass** [Benik/NutsAndBolts#3] opened 2024-02-01 01:56 UTC
This issue was reported on Curseforge a few years back but I assume this might be a better place to bring it up - after a pet battle, the strata of the ElvUI panels is too high causing it to cover ElvUI chat, details, action bars, etc. A reload fixes this - and if you remove the panel, everything is there hidden behind it

Before:
![image](https://github.com/Benik/NutsAndBolts/assets/58087519/71800542-c8e2-4fc1-866a-7a3c3ee6a4b6)

During:
![image](https://github.com/Benik/NutsAndBolts/assets/58087519/b42546a5-c2d4-4800-97dd-990e29dc5aab)

After:
![image](https://github.com/Benik/NutsAndBolts/assets/58087519/439cd3e5-42cb-494d-99c3-eb05b061bad9)

**Comment by Benik** [comment] 2024-02-05 15:20
I'm unable to reproduce your issue with or without Nuts & Bolts

**Comment by lyledouglass** [comment] 2024-02-20 14:29
I will test with only ElvUI and Nut & Bolts again tonight and make sure I can replicate it, but it's been a consistent issue for a few years for me, and I wasn't the original reporter on Curseforge so there must be some common thread

**Comment by lyledouglass** [comment] 2024-02-21 13:32
I was able to replicate this with only base ElvUI and Nuts & Bolts. I recorded a quick vid of it to show the behavior and how I have the panel set up: https://youtu.be/PtNPEvn3KDE?si=nsfwvYxtCDDvZUHP

**Comment by Benik** [comment] 2024-02-21 17:49
I managed to reproduce the issue. I was testing with BenikUI enabled :P
Anyway, it should be fixed with the dev version and will be part of the next version.
You can test by installing manually the dev version from https://github.com/Benik/NutsAndBolts/archive/refs/heads/development.zip

Thank you for grabbing this

**Closed as completed by Benik** 2024-02-21 17:49 UTC
Labels: bug, confirmed, fixed
